# Generated by Django 5.1.6 on 2025-02-27 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='release',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Elie Hmc (Default)', max_length=200, null=True)),
                ('title', models.CharField(default='Elie Hmc (Default)', max_length=200, null=True)),
                ('desc', models.CharField(default='Hey there is a default text about you that yu can change.', max_length=200, null=True)),
                ('profile_img', models.ImageField(blank=True, default='img/logo.jpg', null=True, upload_to='images ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.DeleteModel(
            name='Release',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
